// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:07e42873-d470-4734-8b01-a80a40ebcd88",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_TzBtSu4YK",
    "aws_user_pools_web_client_id": "2972rb1hm2labi4hh95khavic6",
    "oauth": {}
};


export default awsmobile;
